### ISSUE TITLE
Undefined message in method with reverse-proxy

### ISSUE THREAD

**Issue by ebcFlagman** [fabriciobastian/jsonrpc-client-websocket#18]
I have to applications, a server which provides a JSONRpc-Server and a Angular UI (NGINX).
Both applications runs in a docker-compose file and I've configured the NGINX to act as an reverse-proxy

```
  location /rpc {
    proxy_pass http://rpc-server:8080;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
  }
```

You're library connects to ws://localhost/rpc

Now when the server calls a method on the UI, then I get a undefined object. When I did the same from a local deployed UI, then it works all fine.

I also see the incoming messages on the websocket and these are correct.

Any ideas, what the problem could be?

**Comment by fabricio-bastian** [comment]
Let me see if understand you correctly. 

You have a server (running a jsonrpc 2.0 server, with another package) and a UI (using the jsonrpc-client-websocket package). When you call it locally everything works, but when you call remotely it doesn't. And when calling remotely you still see that the UI is delivering the correct messages in the browser dev tools, but you get an undefined object in the server?

**Comment by ebcFlagman** [comment]
I will explain it a little bit more.

Both local: OK
UI local, Server in Docker: OK
Both in Docker: NOK
![image](https://user-images.githubusercontent.com/1026771/180141847-8946a7d9-2e8e-460c-ad4f-a6b1bb7357af.png)

But in the websocket I see correct incoming messages (see healthChanged method)
![image](https://user-images.githubusercontent.com/1026771/180161343-fbba649e-11a3-405c-a46f-9f887496eb41.png)

```
server {
  location / {
    root /srv/app;
    try_files $uri $uri/ /index.html;
  }

  location /rpc {
    proxy_pass http://rpc-proxy:8080/rpc;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
```

**Comment by ebcFlagman** [comment]
Sorry, It was to eraly this morning and I think it was solved :see_no_evil: 
I've edited the post above with detailed informations

**Comment by fabricio-bastian** [comment]
It seems like the package is working as it should, since the messages are being received and dispatched correctly from your UI client. 
Maybe you have some configuration issues on your server or on your JSONRPC server package?
Could it be CORS issues? WS does not have CORS built-in but maybe the package that you are using is checking the origin or implementing some kind of security that you have to configure?

**Comment by ebcFlagman** [comment]
It's curious because we receive the message on the websocket, so I think it isn't a problem of the server side.
I've also added as a test the https://github.com/elpheria/rpc-websockets and I receive the message correctly from the server.

**Comment by fabricio-bastian** [comment]
OK. But the screenshot that you have uploaded shows the messages flowing correctly on the browser. So it seems like the client is responding correctly, but the server is somehow not receiving it.

**Comment by ebcFlagman** [comment]
I talk about the first message in the screenshot it's a method call from the server to the client. So for my understanding the client (browser) get the correct message via websocket but then the json-rpc flow make something with it i don't understand. Probably I can debug it in the afternoon

**Comment by ebcFlagman** [comment]
I started a debug session and I found a problem.
Here's the code snippet from the debug session in docker:
![image](https://user-images.githubusercontent.com/1026771/180216046-7b1bdfe3-a644-4b68-b471-c3d7ad5a0486.png)

And here when I have the UI local and connecto to server in docker:
![image](https://user-images.githubusercontent.com/1026771/180216268-622cf07d-f448-4ea5-855f-c57089cf0799.png)

This leads that it can't get the parameter names:
![image](https://user-images.githubusercontent.com/1026771/180221244-fa9bdbdb-6a06-4969-9cf0-654b46032fcb.png)

**Comment by fabricio-bastian** [comment]
Are you obfuscating your code? Could it be that the method parameters are getting obfuscated?

You could try with positional arguments, that should work in this case. Otherwise, you'll have to remove the classes that are registering methods from obsfuscation/minification.

**Comment by ebcFlagman** [comment]
Thanks for the hint, now I've disabled optimization and buildOptimizer and now it's working fine.
Here's the adaption of my angular.json
```json
"optimization": {
  "scripts": false
 },
"buildOptimizer": false,
```

Or you know how to exclude only one class from optimization?

**Comment by fabricio-bastian** [comment]
No problems. Interesting problem, I guess I'll try to look into an alternative way to register functions as well, once I get some time.
I think that it is possible to exclude specific files from the minification. But I don't have a solution handy for you. 
Feel free to post it here if you find one, and I'll add it to the docs.

**Comment by ebcFlagman** [comment]
Thanks for the reply, I will check if I can find a more specific solution. But for the moment it's fine for me.
I hope you find an alternative for registering method when you have time for it.

**Comment by fabriciobastian** [comment]
Thanks for reporting and for the insights.

As an alternative, in case you want to use the optimization, you could try to register the methods as follows:

```ts
websocket.on('sum', (params: { a: number, b: number }) => { return params.a + params.b; });
```
Then you can stil use named parameters, but with an object instead.

**Comment by ebcFlagman** [comment]
This won't work for me same behaviour as before

**Comment by fabriciobastian** [comment]
It should work if you call it with positional arguments using the object. 

```ts
websocket.call('sum', [{ a: 1, b: 2 }])
  .then((response) => { // handle response })
  .catch((error) => { // handle error });
```
